/**
 * Resolve the register's venue strings to coordinates, once.
 *
 * The register publishes a venue name and sometimes a street, never a lat/lng.
 * Rather than geocoding at runtime — which needs a key, a quota and a network
 * round trip per card — this asks OpenStreetMap's Nominatim once at build time
 * and commits the answer. The app then reads a plain lookup table.
 *
 * Nominatim's usage policy asks for one request per second and a real
 * User-Agent, both honoured below. Anything it cannot place is simply left out,
 * and the app falls back to the record's region centre — a pin in the right
 * town beats a pin in the wrong ocean.
 *
 * It reads the ORIGINAL register rather than the seed, because the register
 * carries a street address and a postcode that the seed's single `location`
 * line drops — and a street resolves where a venue name does not. Nominatim has
 * never heard of "Pakalana Room"; it knows 4344 Hardy St perfectly well.
 *
 *   node tools/geocode-venues.mjs <register.json> app/imports/ui/utilities/venues.js
 */
import fs from 'fs';

const [, , SEED, OUT] = process.argv;
if (!SEED || !OUT) {
  console.error('usage: node tools/geocode-venues.mjs <seed.json> <out.js>');
  process.exit(1);
}

const reg = JSON.parse(fs.readFileSync(SEED, 'utf8'));
const records = ['events', 'recurring_community_happenings', 'clubs_and_groups']
  .flatMap(key => reg[key] || []);

/**
 * Key by the same string the importer writes as `location`, so the app can look
 * a venue up by what is actually on the record — while keeping the address and
 * town alongside, which are what we search on.
 */
const venues = new Map();
for (const record of records) {
  const place = record.location || {};
  const name = (place.venue || place.address_line_1 || '').trim();
  if (name && !venues.has(name)) {
    venues.set(name, {
      address: place.address_line_1 || null,
      city: place.city || null,
      postal: place.postal_code || null,
      region: place.region || null,
    });
  }
}

// Kauaʻi's bounding box. Anything outside it is a wrong match, not a venue —
// "Kukui Grove Center" will happily resolve to a mall in another state.
const BOUNDS = { minLat: 21.85, maxLat: 22.26, minLng: -159.80, maxLng: -159.28 };
const inBounds = p => p.lat >= BOUNDS.minLat && p.lat <= BOUNDS.maxLat
  && p.lng >= BOUNDS.minLng && p.lng <= BOUNDS.maxLng;

const sleep = ms => new Promise(resolve => { setTimeout(resolve, ms); });

const lookup = async query => {
  const url = new URL('https://nominatim.openstreetmap.org/search');
  url.searchParams.set('q', query);
  url.searchParams.set('format', 'json');
  url.searchParams.set('limit', '1');
  // Kauaʻi only, so a same-named mainland venue cannot win.
  url.searchParams.set('viewbox', `${BOUNDS.minLng},${BOUNDS.maxLat},${BOUNDS.maxLng},${BOUNDS.minLat}`);
  url.searchParams.set('bounded', '1');
  const response = await fetch(url, {
    headers: { 'User-Agent': 'MatchBook/1.0 (Kauai community directory; build-time venue geocoding)' },
  });
  if (!response.ok) {
    return null;
  }
  const [hit] = await response.json();
  return hit ? { lat: Number(hit.lat), lng: Number(hit.lon) } : null;
};

const resolved = {};
let found = 0;
let missed = 0;
const names = [...venues.keys()];

for (const [index, name] of names.entries()) {
  const place = venues.get(name);
  // Most specific first. A street address is the reliable one; the venue name
  // is a bonus when OSM happens to know the building; the town is the floor,
  // and still beats a region centre because it is the actual town.
  const attempts = [
    place.address && `${place.address}, ${place.city || ''} HI ${place.postal || ''}`,
    `${name}, ${place.city || 'Kauai'}, Hawaii`,
    place.city && `${place.city}, Hawaii`,
  ].filter(Boolean);
  let point = null;
  for (const attempt of attempts) {
    /* eslint-disable no-await-in-loop */
    point = await lookup(attempt);
    await sleep(1100);
    /* eslint-enable no-await-in-loop */
    if (point && inBounds(point)) {
      break;
    }
    point = null;
  }
  if (point) {
    resolved[name] = { lat: Number(point.lat.toFixed(5)), lng: Number(point.lng.toFixed(5)) };
    found += 1;
  } else {
    missed += 1;
  }
  process.stdout.write(`\r  ${index + 1}/${names.length}  found ${found}  unplaced ${missed}   `);
}

const body = Object.entries(resolved)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, point]) => `  ${JSON.stringify(name)}: { lat: ${point.lat}, lng: ${point.lng} },`)
  .join('\n');

fs.writeFileSync(OUT, `/**
 * Venue coordinates, geocoded once from OpenStreetMap and committed.
 *
 * Generated by tools/geocode-venues.mjs — do not hand-edit; re-run it instead.
 * ${found} of ${names.length} venue strings resolved inside Kauaʻi's bounds. The rest are
 * absent on purpose: a record whose venue is not here falls back to its region
 * centre, which puts the pin in the right town rather than nowhere.
 */
export const VENUES = {
${body}
};
`);

console.log(`\n\nwrote ${OUT}`);
console.log(`${found} placed, ${missed} left to their region`);
